# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

## Build Executor Variables
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
parch_mapping=2023.09.03
cloth_config_version=11.1.118

# Forge
forge_version=47.4.10
forge_loader_version_range=[47,)
forge_version_range=[47,)

# Fabric
# check these on https://fabricmc.net/develop
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.18.1

# Mod options
mod_id=teamshudplus
mod_name=TeamsHUDPlus
mod_license=GNU Affero General Public License v3.0
mod_version=1.6.0
mod_group_id=com.xxinvictus
mod_authors=XxInvictus, Tfarcenim, CommodoreThrawn
mod_description=Continuance of mods by Tfarcenim (TeamsHUDPlus) and CommodoreThrawn (Teams). A mod that displays your team's health and status on the HUD.
issue_tracker_url=https://github.com/XxInvictus/TeamsHUDPlus/issues